GET http://localhost:5000/api/exercises

###

GET http://localhost:5000/api/exercises/23

###

GET http://localhost:5000/api/routines

###

GET http://localhost:5000/api/routines/1

###

POST http://localhost:5000/api/routines
Content-Type: application/json

{
  
}
